services:
  node:
    container_name: "node"
    build: ./node
    ports:
      - "3000:3000"
    networks:
      - rete
    depends_on:
      - mysql
  
  mysql:
    container_name: "mysql"
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cisco
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rete
  
  nginx:
    container_name: "nginx"
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - node    
    
volumes:
  mysql_data:

networks:
  rete:
    driver: bridge